name: CI

on:
  push:
    branches:
      - master
      - 'stage/**' # branch pattern for general changes
  pull_request:
    branches:
      - master
  # Enable running this workflow manually from the Actions tab
  workflow_dispatch:

# GITHUB_TOKEN permissions needed for deployment (copied from pages.yaml)
permissions:
  contents: read
  deployments: none
  pull-requests: write
  statuses: write

jobs:
  index:
    name: Index
    uses: ./.github/workflows/index.yaml
  testbed:
    needs: index
    name: Testbed
    uses: ./.github/workflows/testbed.yaml
  pages:
    needs: [index, testbed]
    name: Pages
    uses: ./.github/workflows/pages.yaml
