name: CI

on:
  push:
    branches:
      - master
      - 'stage/**' # branch pattern for general changes
  pull_request:
    branches:
      - master
  # Enable running this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      index-repo:
        description: "Registry index repository"
        type: string
        required: false
        default: leanprover/reservoir-index
      reindex:
        description: "Reindex packages"
        type: boolean
        required: false
        default: false
      testbed-pattern:
        description: "Regex search for packages to test"
        type: string
        required: true
        default: ".*"
      testbed-toolchain:
        description: "Lean toolchain(s) to test against"
        type: string
        required: true
        default: latest
      testbed-size:
        description: "Max number of testbed entries"
        type: number
        required: true
        default: 256
      save-testbed:
        description: "Save testbed results to index"
        type: boolean
        required: false
        default: false
      production-deploy:
        description: "Deploy website to production"
        type: boolean
        required: false
        default: false

# GITHUB_TOKEN permissions needed for deployment (copied from website.yml)
permissions:
  contents: read
  pull-requests: write
  statuses: write

# Permit only 1 concurrent run per branch when triggered automatically, cancelling previous ones.
concurrency:
  group: ci/${{ github.event_name == 'workflow_dispatch' && github.run_id || github.ref_name }}
  cancel-in-progress: true

jobs:
  config:
    name: Configure
    runs-on: ubuntu-latest
    outputs:
      index-repo: ${{ steps.compute.outputs.index-repo }}
      run-testbed: ${{ steps.compute.outputs.run-testbed }}
      testbed-size: ${{ steps.compute.outputs.testbed-size }}
      production-deploy: ${{ steps.compute.outputs.production-deploy }}
    steps:
      # We echo these values out to make failures easier to debug from the logs
      - id: compute
        name: Compute Configuration
        run: |
          echo index-repo=${{ inputs.index-repo || (github.ref_name == 'master' && 'leanprover/reservoir-index' || '') }} >> "$GITHUB_OUTPUT"
          echo run-testbed=${{ inputs.testbed-size == null && github.ref_name != 'master' || inputs.testbed-size != 0 }} >> "$GITHUB_OUTPUT"
          echo testbed-size=${{ inputs.testbed-size == null && 20 || inputs.testbed-size }} >> "$GITHUB_OUTPUT"
          echo production-deploy=${{ inputs.production-deploy || (toJson(inputs.production-deploy) == 'null' && github.ref_name == 'master') }} >> "$GITHUB_OUTPUT"
  index:
    name: Index
    needs: [config]
    if: (!needs.config.outputs.index-repo || inputs.reindex)
    uses: ./.github/workflows/index.yml
    secrets: inherit
    with:
      repository: ${{ inputs.reindex && inputs.index-repo || '' }}
  testbed:
    needs: [config, index]
    # Run even if `index` is skipped
    if: (!failure() && !cancelled() && needs.config.outputs.run-testbed == 'true')
    name: Testbed
    uses: ./.github/workflows/testbed.yml
    secrets: inherit
    with:
      index-repo: ${{ needs.config.outputs.index-repo }}
      pattern: ${{ inputs.testbed-pattern || '.*' }}
      toolchain: ${{ inputs.testbed-toolchain || 'latest,package' }}
      max-size: ${{ fromJson(needs.config.outputs.testbed-size) }}
      update-index: ${{ inputs.save-testbed == true }}
      dev: ${{ github.event_name != 'workflow_dispatch' }}
  website:
    needs: [config, index, testbed]
    # Run even if `index` or `testbed` is skipped
    if: (!failure() && !cancelled())
    name: Website
    uses: ./.github/workflows/website.yml
    secrets: inherit
    with:
      index-repo: ${{ needs.config.outputs.index-repo }}
      testbed-artifact: ${{ !(needs.config.outputs.index-repo && inputs.save-testbed) && needs.config.outputs.run-testbed == 'true' }}
      production-deploy: ${{ needs.config.outputs.production-deploy == 'true' }}
