name: Index

on:
  push:
    branches:
      - 'index/**' # branch pattern for query-only changes
  # Enable running this workflow from ci.yml
  workflow_call:
    inputs:
      repository:
        description: "Registry index repository to update"
        type: string
        required: false
  # Enable running this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      repository:
        description: "Registry index repository to update"
        type: string
        required: false
        default: leanprover/reservoir-index

# Permit only 1 concurrent update of the same index repository, cancelling previous ones.
concurrency:
  group: ${{ inputs.repository && format('index/{0}', inputs.repository) || github.run_id }}
  cancel-in-progress: true

jobs:
  index:
    name: ${{ inputs.repository && 'Update' || 'Fetch' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Checkout Index Repository
        if: inputs.repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PUSH_RESERVOIR_INDEX_TOKEN }}
          repository: ${{ inputs.repository }}
          path: index
      - name: Query Repositories
        run: |
          ./query.py -v \
            ${{ inputs.repository && '-D index' || '-o index.json' }} \
            -L ${{ (!inputs.repository && github.ref_name != 'master') && 100 || -1 }}
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Update Index Repository
        if: inputs.repository
        uses: EndBug/add-and-commit@v9
        with:
          cwd: index
          fetch: false
          message: |
            chore: update index

            ${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}/attempts/${{github.run_attempt}}
          default_author: github_actions
      - name: Upload Index Artifact
        if: (!inputs.repository)
        uses: actions/upload-artifact@v3
        with:
          name: index
          path: index.json
          if-no-files-found: error
